
import java.awt.*;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JPanel;

/*
 * Basic JFrame that uses buttons to change the location of something
 * drawn on a graphics panel.
 * 
 */
public class MyGraphicsJFrame extends javax.swing.JFrame {

    private MyGraphicsPanel myGraphicsPanel;
    
    /**
     * Creates new form MyGraphicsJFrame
     */
    public MyGraphicsJFrame() {
        initComponents();        
        myGraphicsPanel = new MyGraphicsPanel();        
        int WIDTH = 1000;
        setSize(WIDTH,700);
        Picture temp = new Picture("umu.png");
        myGraphicsPanel.setBackground(Color.GRAY);      
        myGraphicsPanel.setSize(WIDTH-20,700);
        myGraphicsPanel.setLocation(10,10);
        add(myGraphicsPanel);         
    }
    

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 519, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 294, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyGraphicsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyGraphicsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyGraphicsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyGraphicsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyGraphicsJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    public void paintOnBica(boolean b){
        myGraphicsPanel.setHasBica(b);
    }
    
    void paintOnHPCC(boolean b) {
       myGraphicsPanel.setHasHPCC(b);
    }

    void paintOnKetcham(boolean b) {
     myGraphicsPanel.setHasKetcham(b);    
    }

    void paintOnShields(boolean b) {
    myGraphicsPanel.setHasShields(b);    
    }

    void paintOnMcMaster(boolean b) {
    myGraphicsPanel.setHasMcMaster(b);    
    }

    void paintOnHartshorn(boolean b) {
        myGraphicsPanel.setHasHartshorn(b);
    }
}
